### PR TITLE
Load all type strategies at run

### PR DESCRIPTION
**Pull request by Fluidbyte**

### CODE REVIEW

**Comment by TomFrost** [comment]
To simplify paths and includes, instead of... ```
types/
  strategies/
    array.js
    object.js
    etc.js
  index.js
types.js
```
we could do
```
typeStrategies/
  array.js
  object.js
  index.js
  etc.js
types.js
```
And now in types.js you can do
```
import typeStrategies from './typeStrategies'
```

**Comment by TomFrost** [comment]
I showered.

`typedefs`

**Comment by TomFrost** [comment]
This is ok, but I don't like that you used camelCase.

**Comment by Fluidbyte** [comment]
@TomFrost I don't like to spread hate on OSS projects, but keep in mind, you're in range to receive a hearty throat punch

**Comment by TomFrost** [comment]
:joy:

**Comment by TomFrost** [comment]
(that was my accept-emoji)

**Pull request merged**
